print(3 + 4)
print(3 - 4)
print(3 * 4)
print(3 / 4)
print(4 % 2)
print(3**4)
print(8 // 3)

print("Imam")
print("Haq")
print("England")
print("I am enjoying 30 days of python")
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(["Asabeneh", "Python", "Finland"]))
print(type("Imam"))
print(type("Haq"))
print(type("England"))

x = (8**2) + (5**2)
print(x)
print(math.sqrt(x))
