tpl = ()
siblings = ("Ruji", "Runi", "Mizan", "Ijal")
print("Number of siblings:", len(siblings))
family_members = list(siblings)
family_members.append("Abdul")
family_members.append("Badana")
print("Family Members:", family_members)
siblings = family_members.copy()
parents = family_members.copy()
siblings.remove("Abdul")
siblings.remove("Badana")
parents.remove("Ruji")
parents.remove("Runi")
parents.remove("Mizan")
parents.remove("Ijal")
print("Siblings:", siblings)
print("Parents:", parents)
